installdir = $(pkglibdir)
plugindir = $(libdir)/enigma2/python/Components
pluginexecdir = $(libdir)/enigma2/python/Components
pluginexec_PROGRAMS = createapscfiles
createapscfiles_SOURCES = timeshift/createapscfiles.cc
